package rebue.kdi.mo;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import java.util.Date;
import org.springframework.format.annotation.DateTimeFormat;

/**
 * Database Table Remarks:
 *   物流订单
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table KDI_LOGISTIC
 *
 * @mbg.generated do_not_delete_during_merge 2018-06-08 09:50:07
 */
@ApiModel(value = "KdiLogisticMo", description = "物流订单")
@JsonInclude(Include.NON_NULL)
public class KdiLogisticMo implements Serializable {
    /**
     * Database Column Remarks:
     *   物流订单ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KDI_LOGISTIC.ID
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    @ApiModelProperty(value = "物流订单ID")
    private Long id;

    /**
     * Database Column Remarks:
     *   快递公司编码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KDI_LOGISTIC.SHIPPER_CODE
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    @ApiModelProperty(value = "快递公司编码")
    private String shipperCode;

    /**
     * Database Column Remarks:
     *   物流订单号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KDI_LOGISTIC.LOGISTIC_CODE
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    @ApiModelProperty(value = "物流订单号")
    private String logisticCode;

    /**
     * Database Column Remarks:
     *   物流订单状态
     *               0-无轨迹
     *               1-已揽收
     *               2-在途中 201-到达派件城市 202-派件中 211-已放入快递柜或驿站
     *               3-已签收 311-已取出快递柜或驿站
     *               4-问题件 401-发货无信息 402-超时未签收 403-超时未更新 404-拒收(退件) 412-快递柜或驿站超时未取
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KDI_LOGISTIC.LOGISTIC_STATUS
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    @ApiModelProperty(value = "物流订单状态\n"
             +"            0-无轨迹\n"
             +"            1-已揽收\n"
             +"            2-在途中 201-到达派件城市 202-派件中 211-已放入快递柜或驿站\n"
             +"            3-已签收 311-已取出快递柜或驿站\n"
             +"            4-问题件 401-发货无信息 402-超时未签收 403-超时未更新 404-拒收(退件) 412-快递柜或驿站超时未取")
    private String logisticStatus;

    /**
     * Database Column Remarks:
     *   下单时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KDI_LOGISTIC.ORDER_TIME
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    @ApiModelProperty(value = "下单时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date orderTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KDI_LOGISTIC.UPDATE_TIME
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    @ApiModelProperty(value = "更新时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   预计到达时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KDI_LOGISTIC.ESTIMATED_ARRIVAL_TIME
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    @ApiModelProperty(value = "预计到达时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date estimatedArrivalTime;

    /**
     * Database Column Remarks:
     *   所在城市
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KDI_LOGISTIC.CITY
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    @ApiModelProperty(value = "所在城市")
    private String city;

    /**
     * Database Column Remarks:
     *   支付类型
     *               运费支付方式:
     *               1-现付
     *               2-到付
     *               3-月结
     *               4-第三方付
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KDI_LOGISTIC.PAY_TYPE
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    @ApiModelProperty(value = "支付类型\n"
             +"            运费支付方式:\n"
             +"            1-现付\n"
             +"            2-到付\n"
             +"            3-月结\n"
             +"            4-第三方付")
    private Byte payType;

    /**
     * Database Column Remarks:
     *   快递类型
     *               1-标准快件
     *               
     *               详细快递类型参考《快递公司快递业务类型.xlsx》
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KDI_LOGISTIC.EXP_TYPE
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    @ApiModelProperty(value = "快递类型\n"
             +"            1-标准快件\n"
             +"            详细快递类型参考《快递公司快递业务类型.xlsx》")
    private Byte expType;

    /**
     * Database Column Remarks:
     *   订单ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KDI_LOGISTIC.ORDER_ID
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    @ApiModelProperty(value = "订单ID")
    private Long orderId;

    /**
     * Database Column Remarks:
     *   订单标题
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KDI_LOGISTIC.ORDER_TITLE
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    @ApiModelProperty(value = "订单标题")
    private String orderTitle;

    /**
     * Database Column Remarks:
     *   订单详情
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KDI_LOGISTIC.ORDER_DETAIL
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    @ApiModelProperty(value = "订单详情")
    private String orderDetail;

    /**
     * Database Column Remarks:
     *   发件人名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KDI_LOGISTIC.SENDER_NAME
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    @ApiModelProperty(value = "发件人名称")
    private String senderName;

    /**
     * Database Column Remarks:
     *   发件人电话
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KDI_LOGISTIC.SENDER_TEL
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    @ApiModelProperty(value = "发件人电话")
    private String senderTel;

    /**
     * Database Column Remarks:
     *   发件人手机
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KDI_LOGISTIC.SENDER_MOBILE
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    @ApiModelProperty(value = "发件人手机")
    private String senderMobile;

    /**
     * Database Column Remarks:
     *   发件省
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KDI_LOGISTIC.SENDER_PROVINCE
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    @ApiModelProperty(value = "发件省")
    private String senderProvince;

    /**
     * Database Column Remarks:
     *   发件市
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KDI_LOGISTIC.SENDER_CITY
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    @ApiModelProperty(value = "发件市")
    private String senderCity;

    /**
     * Database Column Remarks:
     *   发件区
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KDI_LOGISTIC.SENDER_EXP_AREA
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    @ApiModelProperty(value = "发件区")
    private String senderExpArea;

    /**
     * Database Column Remarks:
     *   发件人详细地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KDI_LOGISTIC.SENDER_ADDRESS
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    @ApiModelProperty(value = "发件人详细地址")
    private String senderAddress;

    /**
     * Database Column Remarks:
     *   发件地邮编
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KDI_LOGISTIC.SENDER_POST_CODE
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    @ApiModelProperty(value = "发件地邮编")
    private String senderPostCode;

    /**
     * Database Column Remarks:
     *   收件人名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KDI_LOGISTIC.RECEIVER_NAME
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    @ApiModelProperty(value = "收件人名称")
    private String receiverName;

    /**
     * Database Column Remarks:
     *   收件人电话
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KDI_LOGISTIC.RECEIVER_TEL
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    @ApiModelProperty(value = "收件人电话")
    private String receiverTel;

    /**
     * Database Column Remarks:
     *   收件人手机
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KDI_LOGISTIC.RECEIVER_MOBILE
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    @ApiModelProperty(value = "收件人手机")
    private String receiverMobile;

    /**
     * Database Column Remarks:
     *   收件省
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KDI_LOGISTIC.RECEIVER_PROVINCE
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    @ApiModelProperty(value = "收件省")
    private String receiverProvince;

    /**
     * Database Column Remarks:
     *   收件市
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KDI_LOGISTIC.RECEIVER_CITY
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    @ApiModelProperty(value = "收件市")
    private String receiverCity;

    /**
     * Database Column Remarks:
     *   收件区
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KDI_LOGISTIC.RECEIVER_EXP_AREA
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    @ApiModelProperty(value = "收件区")
    private String receiverExpArea;

    /**
     * Database Column Remarks:
     *   收件人详细地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KDI_LOGISTIC.RECEIVER_ADDRESS
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    @ApiModelProperty(value = "收件人详细地址")
    private String receiverAddress;

    /**
     * Database Column Remarks:
     *   收件地邮编
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KDI_LOGISTIC.RECEIVER_POST_CODE
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    @ApiModelProperty(value = "收件地邮编")
    private String receiverPostCode;

    /**
     * Database Column Remarks:
     *   打印页面
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KDI_LOGISTIC.PRINT_PAGE
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    @ApiModelProperty(value = "打印页面")
    private String printPage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table KDI_LOGISTIC
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KDI_LOGISTIC.ID
     *
     * @return the value of KDI_LOGISTIC.ID
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KDI_LOGISTIC.ID
     *
     * @param id the value for KDI_LOGISTIC.ID
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KDI_LOGISTIC.SHIPPER_CODE
     *
     * @return the value of KDI_LOGISTIC.SHIPPER_CODE
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    public String getShipperCode() {
        return shipperCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KDI_LOGISTIC.SHIPPER_CODE
     *
     * @param shipperCode the value for KDI_LOGISTIC.SHIPPER_CODE
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    public void setShipperCode(String shipperCode) {
        this.shipperCode = shipperCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KDI_LOGISTIC.LOGISTIC_CODE
     *
     * @return the value of KDI_LOGISTIC.LOGISTIC_CODE
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    public String getLogisticCode() {
        return logisticCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KDI_LOGISTIC.LOGISTIC_CODE
     *
     * @param logisticCode the value for KDI_LOGISTIC.LOGISTIC_CODE
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    public void setLogisticCode(String logisticCode) {
        this.logisticCode = logisticCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KDI_LOGISTIC.LOGISTIC_STATUS
     *
     * @return the value of KDI_LOGISTIC.LOGISTIC_STATUS
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    public String getLogisticStatus() {
        return logisticStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KDI_LOGISTIC.LOGISTIC_STATUS
     *
     * @param logisticStatus the value for KDI_LOGISTIC.LOGISTIC_STATUS
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    public void setLogisticStatus(String logisticStatus) {
        this.logisticStatus = logisticStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KDI_LOGISTIC.ORDER_TIME
     *
     * @return the value of KDI_LOGISTIC.ORDER_TIME
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    public Date getOrderTime() {
        return orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KDI_LOGISTIC.ORDER_TIME
     *
     * @param orderTime the value for KDI_LOGISTIC.ORDER_TIME
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    public void setOrderTime(Date orderTime) {
        this.orderTime = orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KDI_LOGISTIC.UPDATE_TIME
     *
     * @return the value of KDI_LOGISTIC.UPDATE_TIME
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KDI_LOGISTIC.UPDATE_TIME
     *
     * @param updateTime the value for KDI_LOGISTIC.UPDATE_TIME
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KDI_LOGISTIC.ESTIMATED_ARRIVAL_TIME
     *
     * @return the value of KDI_LOGISTIC.ESTIMATED_ARRIVAL_TIME
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    public Date getEstimatedArrivalTime() {
        return estimatedArrivalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KDI_LOGISTIC.ESTIMATED_ARRIVAL_TIME
     *
     * @param estimatedArrivalTime the value for KDI_LOGISTIC.ESTIMATED_ARRIVAL_TIME
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    public void setEstimatedArrivalTime(Date estimatedArrivalTime) {
        this.estimatedArrivalTime = estimatedArrivalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KDI_LOGISTIC.CITY
     *
     * @return the value of KDI_LOGISTIC.CITY
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KDI_LOGISTIC.CITY
     *
     * @param city the value for KDI_LOGISTIC.CITY
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KDI_LOGISTIC.PAY_TYPE
     *
     * @return the value of KDI_LOGISTIC.PAY_TYPE
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    public Byte getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KDI_LOGISTIC.PAY_TYPE
     *
     * @param payType the value for KDI_LOGISTIC.PAY_TYPE
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    public void setPayType(Byte payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KDI_LOGISTIC.EXP_TYPE
     *
     * @return the value of KDI_LOGISTIC.EXP_TYPE
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    public Byte getExpType() {
        return expType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KDI_LOGISTIC.EXP_TYPE
     *
     * @param expType the value for KDI_LOGISTIC.EXP_TYPE
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    public void setExpType(Byte expType) {
        this.expType = expType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KDI_LOGISTIC.ORDER_ID
     *
     * @return the value of KDI_LOGISTIC.ORDER_ID
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KDI_LOGISTIC.ORDER_ID
     *
     * @param orderId the value for KDI_LOGISTIC.ORDER_ID
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KDI_LOGISTIC.ORDER_TITLE
     *
     * @return the value of KDI_LOGISTIC.ORDER_TITLE
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    public String getOrderTitle() {
        return orderTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KDI_LOGISTIC.ORDER_TITLE
     *
     * @param orderTitle the value for KDI_LOGISTIC.ORDER_TITLE
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    public void setOrderTitle(String orderTitle) {
        this.orderTitle = orderTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KDI_LOGISTIC.ORDER_DETAIL
     *
     * @return the value of KDI_LOGISTIC.ORDER_DETAIL
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    public String getOrderDetail() {
        return orderDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KDI_LOGISTIC.ORDER_DETAIL
     *
     * @param orderDetail the value for KDI_LOGISTIC.ORDER_DETAIL
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    public void setOrderDetail(String orderDetail) {
        this.orderDetail = orderDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KDI_LOGISTIC.SENDER_NAME
     *
     * @return the value of KDI_LOGISTIC.SENDER_NAME
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    public String getSenderName() {
        return senderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KDI_LOGISTIC.SENDER_NAME
     *
     * @param senderName the value for KDI_LOGISTIC.SENDER_NAME
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    public void setSenderName(String senderName) {
        this.senderName = senderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KDI_LOGISTIC.SENDER_TEL
     *
     * @return the value of KDI_LOGISTIC.SENDER_TEL
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    public String getSenderTel() {
        return senderTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KDI_LOGISTIC.SENDER_TEL
     *
     * @param senderTel the value for KDI_LOGISTIC.SENDER_TEL
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    public void setSenderTel(String senderTel) {
        this.senderTel = senderTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KDI_LOGISTIC.SENDER_MOBILE
     *
     * @return the value of KDI_LOGISTIC.SENDER_MOBILE
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    public String getSenderMobile() {
        return senderMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KDI_LOGISTIC.SENDER_MOBILE
     *
     * @param senderMobile the value for KDI_LOGISTIC.SENDER_MOBILE
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    public void setSenderMobile(String senderMobile) {
        this.senderMobile = senderMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KDI_LOGISTIC.SENDER_PROVINCE
     *
     * @return the value of KDI_LOGISTIC.SENDER_PROVINCE
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    public String getSenderProvince() {
        return senderProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KDI_LOGISTIC.SENDER_PROVINCE
     *
     * @param senderProvince the value for KDI_LOGISTIC.SENDER_PROVINCE
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    public void setSenderProvince(String senderProvince) {
        this.senderProvince = senderProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KDI_LOGISTIC.SENDER_CITY
     *
     * @return the value of KDI_LOGISTIC.SENDER_CITY
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    public String getSenderCity() {
        return senderCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KDI_LOGISTIC.SENDER_CITY
     *
     * @param senderCity the value for KDI_LOGISTIC.SENDER_CITY
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    public void setSenderCity(String senderCity) {
        this.senderCity = senderCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KDI_LOGISTIC.SENDER_EXP_AREA
     *
     * @return the value of KDI_LOGISTIC.SENDER_EXP_AREA
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    public String getSenderExpArea() {
        return senderExpArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KDI_LOGISTIC.SENDER_EXP_AREA
     *
     * @param senderExpArea the value for KDI_LOGISTIC.SENDER_EXP_AREA
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    public void setSenderExpArea(String senderExpArea) {
        this.senderExpArea = senderExpArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KDI_LOGISTIC.SENDER_ADDRESS
     *
     * @return the value of KDI_LOGISTIC.SENDER_ADDRESS
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    public String getSenderAddress() {
        return senderAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KDI_LOGISTIC.SENDER_ADDRESS
     *
     * @param senderAddress the value for KDI_LOGISTIC.SENDER_ADDRESS
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    public void setSenderAddress(String senderAddress) {
        this.senderAddress = senderAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KDI_LOGISTIC.SENDER_POST_CODE
     *
     * @return the value of KDI_LOGISTIC.SENDER_POST_CODE
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    public String getSenderPostCode() {
        return senderPostCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KDI_LOGISTIC.SENDER_POST_CODE
     *
     * @param senderPostCode the value for KDI_LOGISTIC.SENDER_POST_CODE
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    public void setSenderPostCode(String senderPostCode) {
        this.senderPostCode = senderPostCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KDI_LOGISTIC.RECEIVER_NAME
     *
     * @return the value of KDI_LOGISTIC.RECEIVER_NAME
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    public String getReceiverName() {
        return receiverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KDI_LOGISTIC.RECEIVER_NAME
     *
     * @param receiverName the value for KDI_LOGISTIC.RECEIVER_NAME
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    public void setReceiverName(String receiverName) {
        this.receiverName = receiverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KDI_LOGISTIC.RECEIVER_TEL
     *
     * @return the value of KDI_LOGISTIC.RECEIVER_TEL
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    public String getReceiverTel() {
        return receiverTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KDI_LOGISTIC.RECEIVER_TEL
     *
     * @param receiverTel the value for KDI_LOGISTIC.RECEIVER_TEL
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    public void setReceiverTel(String receiverTel) {
        this.receiverTel = receiverTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KDI_LOGISTIC.RECEIVER_MOBILE
     *
     * @return the value of KDI_LOGISTIC.RECEIVER_MOBILE
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    public String getReceiverMobile() {
        return receiverMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KDI_LOGISTIC.RECEIVER_MOBILE
     *
     * @param receiverMobile the value for KDI_LOGISTIC.RECEIVER_MOBILE
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    public void setReceiverMobile(String receiverMobile) {
        this.receiverMobile = receiverMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KDI_LOGISTIC.RECEIVER_PROVINCE
     *
     * @return the value of KDI_LOGISTIC.RECEIVER_PROVINCE
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    public String getReceiverProvince() {
        return receiverProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KDI_LOGISTIC.RECEIVER_PROVINCE
     *
     * @param receiverProvince the value for KDI_LOGISTIC.RECEIVER_PROVINCE
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    public void setReceiverProvince(String receiverProvince) {
        this.receiverProvince = receiverProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KDI_LOGISTIC.RECEIVER_CITY
     *
     * @return the value of KDI_LOGISTIC.RECEIVER_CITY
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    public String getReceiverCity() {
        return receiverCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KDI_LOGISTIC.RECEIVER_CITY
     *
     * @param receiverCity the value for KDI_LOGISTIC.RECEIVER_CITY
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    public void setReceiverCity(String receiverCity) {
        this.receiverCity = receiverCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KDI_LOGISTIC.RECEIVER_EXP_AREA
     *
     * @return the value of KDI_LOGISTIC.RECEIVER_EXP_AREA
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    public String getReceiverExpArea() {
        return receiverExpArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KDI_LOGISTIC.RECEIVER_EXP_AREA
     *
     * @param receiverExpArea the value for KDI_LOGISTIC.RECEIVER_EXP_AREA
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    public void setReceiverExpArea(String receiverExpArea) {
        this.receiverExpArea = receiverExpArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KDI_LOGISTIC.RECEIVER_ADDRESS
     *
     * @return the value of KDI_LOGISTIC.RECEIVER_ADDRESS
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    public String getReceiverAddress() {
        return receiverAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KDI_LOGISTIC.RECEIVER_ADDRESS
     *
     * @param receiverAddress the value for KDI_LOGISTIC.RECEIVER_ADDRESS
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    public void setReceiverAddress(String receiverAddress) {
        this.receiverAddress = receiverAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KDI_LOGISTIC.RECEIVER_POST_CODE
     *
     * @return the value of KDI_LOGISTIC.RECEIVER_POST_CODE
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    public String getReceiverPostCode() {
        return receiverPostCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KDI_LOGISTIC.RECEIVER_POST_CODE
     *
     * @param receiverPostCode the value for KDI_LOGISTIC.RECEIVER_POST_CODE
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    public void setReceiverPostCode(String receiverPostCode) {
        this.receiverPostCode = receiverPostCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KDI_LOGISTIC.PRINT_PAGE
     *
     * @return the value of KDI_LOGISTIC.PRINT_PAGE
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    public String getPrintPage() {
        return printPage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KDI_LOGISTIC.PRINT_PAGE
     *
     * @param printPage the value for KDI_LOGISTIC.PRINT_PAGE
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    public void setPrintPage(String printPage) {
        this.printPage = printPage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KDI_LOGISTIC
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", shipperCode=").append(shipperCode);
        sb.append(", logisticCode=").append(logisticCode);
        sb.append(", logisticStatus=").append(logisticStatus);
        sb.append(", orderTime=").append(orderTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", estimatedArrivalTime=").append(estimatedArrivalTime);
        sb.append(", city=").append(city);
        sb.append(", payType=").append(payType);
        sb.append(", expType=").append(expType);
        sb.append(", orderId=").append(orderId);
        sb.append(", orderTitle=").append(orderTitle);
        sb.append(", orderDetail=").append(orderDetail);
        sb.append(", senderName=").append(senderName);
        sb.append(", senderTel=").append(senderTel);
        sb.append(", senderMobile=").append(senderMobile);
        sb.append(", senderProvince=").append(senderProvince);
        sb.append(", senderCity=").append(senderCity);
        sb.append(", senderExpArea=").append(senderExpArea);
        sb.append(", senderAddress=").append(senderAddress);
        sb.append(", senderPostCode=").append(senderPostCode);
        sb.append(", receiverName=").append(receiverName);
        sb.append(", receiverTel=").append(receiverTel);
        sb.append(", receiverMobile=").append(receiverMobile);
        sb.append(", receiverProvince=").append(receiverProvince);
        sb.append(", receiverCity=").append(receiverCity);
        sb.append(", receiverExpArea=").append(receiverExpArea);
        sb.append(", receiverAddress=").append(receiverAddress);
        sb.append(", receiverPostCode=").append(receiverPostCode);
        sb.append(", printPage=").append(printPage);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KDI_LOGISTIC
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        KdiLogisticMo other = (KdiLogisticMo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
        ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KDI_LOGISTIC
     *
     * @mbg.generated 2018-06-08 09:50:07
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        return result;
    }
}