package rebue.kdi.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import rebue.kdi.mo.KdiCompanyMo;
import rebue.robotech.mapper.MybatisBaseMapper;

@Mapper
public interface KdiCompanyMapper extends MybatisBaseMapper<KdiCompanyMo, Long> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KDI_COMPANY
     *
     * @mbg.generated 2018-06-07 15:01:36
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KDI_COMPANY
     *
     * @mbg.generated 2018-06-07 15:01:36
     */
    int insert(KdiCompanyMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KDI_COMPANY
     *
     * @mbg.generated 2018-06-07 15:01:36
     */
    int insertSelective(KdiCompanyMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KDI_COMPANY
     *
     * @mbg.generated 2018-06-07 15:01:36
     */
    KdiCompanyMo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KDI_COMPANY
     *
     * @mbg.generated 2018-06-07 15:01:36
     */
    int updateByPrimaryKeySelective(KdiCompanyMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KDI_COMPANY
     *
     * @mbg.generated 2018-06-07 15:01:36
     */
    int updateByPrimaryKey(KdiCompanyMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KDI_COMPANY
     *
     * @mbg.generated 2018-06-07 15:01:36
     */
    List<KdiCompanyMo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KDI_COMPANY
     *
     * @mbg.generated 2018-06-07 15:01:36
     */
    List<KdiCompanyMo> selectSelective(KdiCompanyMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KDI_COMPANY
     *
     * @mbg.generated 2018-06-07 15:01:36
     */
    boolean existByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KDI_COMPANY
     *
     * @mbg.generated 2018-06-07 15:01:36
     */
    boolean existSelective(KdiCompanyMo record);
}