package rebue.kdi.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import rebue.kdi.mo.KdiCompanyMo;
import rebue.robotech.mapper.MybatisBaseMapper;
import org.apache.ibatis.annotations.Select;

@Mapper
public interface KdiCompanyMapper extends MybatisBaseMapper<KdiCompanyMo, Long> {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table KDI_COMPANY
	 *
	 * @mbg.generated 2018-06-15 16:28:22
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table KDI_COMPANY
	 *
	 * @mbg.generated 2018-06-15 16:28:22
	 */
	int insert(KdiCompanyMo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table KDI_COMPANY
	 *
	 * @mbg.generated 2018-06-15 16:28:22
	 */
	int insertSelective(KdiCompanyMo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table KDI_COMPANY
	 *
	 * @mbg.generated 2018-06-15 16:28:22
	 */
	KdiCompanyMo selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table KDI_COMPANY
	 *
	 * @mbg.generated 2018-06-15 16:28:22
	 */
	int updateByPrimaryKeySelective(KdiCompanyMo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table KDI_COMPANY
	 *
	 * @mbg.generated 2018-06-15 16:28:22
	 */
	int updateByPrimaryKey(KdiCompanyMo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table KDI_COMPANY
	 *
	 * @mbg.generated 2018-06-15 16:28:22
	 */
	List<KdiCompanyMo> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table KDI_COMPANY
	 *
	 * @mbg.generated 2018-06-15 16:28:22
	 */
	List<KdiCompanyMo> selectSelective(KdiCompanyMo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table KDI_COMPANY
	 *
	 * @mbg.generated 2018-06-15 16:28:22
	 */
	boolean existByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table KDI_COMPANY
	 *
	 * @mbg.generated 2018-06-15 16:28:22
	 */
	boolean existSelective(KdiCompanyMo record);

	/**
	 * 查询所有快递公司名称和编码
	 * 
	 * @return
	 */
	@Select("SELECT ID as id, COMPANY_NAME as companyName, COMPANY_CODE as companyCode FROM KDI_COMPANY ORDER BY ENTRY_TIME DESC")
	List<KdiCompanyMo> selectKdiCompanyNameAndCode();
}