package rebue.kdi.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import rebue.kdi.mo.KdiLogisticMo;
import rebue.robotech.mapper.MybatisBaseMapper;

@Mapper
public interface KdiLogisticMapper extends MybatisBaseMapper<KdiLogisticMo, Long> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KDI_LOGISTIC
     *
     * @mbg.generated 2018-04-14 14:07:46
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KDI_LOGISTIC
     *
     * @mbg.generated 2018-04-14 14:07:46
     */
    int insert(KdiLogisticMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KDI_LOGISTIC
     *
     * @mbg.generated 2018-04-14 14:07:46
     */
    int insertSelective(KdiLogisticMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KDI_LOGISTIC
     *
     * @mbg.generated 2018-04-14 14:07:46
     */
    KdiLogisticMo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KDI_LOGISTIC
     *
     * @mbg.generated 2018-04-14 14:07:46
     */
    int updateByPrimaryKeySelective(KdiLogisticMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KDI_LOGISTIC
     *
     * @mbg.generated 2018-04-14 14:07:46
     */
    int updateByPrimaryKeyWithBLOBs(KdiLogisticMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KDI_LOGISTIC
     *
     * @mbg.generated 2018-04-14 14:07:46
     */
    int updateByPrimaryKey(KdiLogisticMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KDI_LOGISTIC
     *
     * @mbg.generated 2018-04-14 14:07:46
     */
    List<KdiLogisticMo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KDI_LOGISTIC
     *
     * @mbg.generated 2018-04-14 14:07:46
     */
    List<KdiLogisticMo> selectSelective(KdiLogisticMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KDI_LOGISTIC
     *
     * @mbg.generated 2018-04-14 14:07:46
     */
    boolean existByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KDI_LOGISTIC
     *
     * @mbg.generated 2018-04-14 14:07:46
     */
    boolean existSelective(KdiLogisticMo record);
}