package rebue.kdi.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import rebue.kdi.mo.KdiSenderMo;
import rebue.robotech.mapper.MybatisBaseMapper;

@Mapper
public interface KdiSenderMapper extends MybatisBaseMapper<KdiSenderMo, Long> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KDI_SENDER
     *
     * @mbg.generated 2018-06-15 16:28:22
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KDI_SENDER
     *
     * @mbg.generated 2018-06-15 16:28:22
     */
    int insert(KdiSenderMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KDI_SENDER
     *
     * @mbg.generated 2018-06-15 16:28:22
     */
    int insertSelective(KdiSenderMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KDI_SENDER
     *
     * @mbg.generated 2018-06-15 16:28:22
     */
    KdiSenderMo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KDI_SENDER
     *
     * @mbg.generated 2018-06-15 16:28:22
     */
    int updateByPrimaryKeySelective(KdiSenderMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KDI_SENDER
     *
     * @mbg.generated 2018-06-15 16:28:22
     */
    int updateByPrimaryKey(KdiSenderMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KDI_SENDER
     *
     * @mbg.generated 2018-06-15 16:28:22
     */
    List<KdiSenderMo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KDI_SENDER
     *
     * @mbg.generated 2018-06-15 16:28:22
     */
    List<KdiSenderMo> selectSelective(KdiSenderMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KDI_SENDER
     *
     * @mbg.generated 2018-06-15 16:28:22
     */
    boolean existByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KDI_SENDER
     *
     * @mbg.generated 2018-06-15 16:28:22
     */
    boolean existSelective(KdiSenderMo record);
}