package rebue.kdi.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import rebue.kdi.mo.KdiTraceMo;
import rebue.robotech.mapper.MybatisBaseMapper;
import org.apache.ibatis.annotations.Delete;

@Mapper
public interface KdiTraceMapper extends MybatisBaseMapper<KdiTraceMo, Long> {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table KDI_TRACE
	 *
	 * @mbg.generated 2018-06-15 17:03:19
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table KDI_TRACE
	 *
	 * @mbg.generated 2018-06-15 17:03:19
	 */
	int insert(KdiTraceMo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table KDI_TRACE
	 *
	 * @mbg.generated 2018-06-15 17:03:19
	 */
	int insertSelective(KdiTraceMo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table KDI_TRACE
	 *
	 * @mbg.generated 2018-06-15 17:03:19
	 */
	KdiTraceMo selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table KDI_TRACE
	 *
	 * @mbg.generated 2018-06-15 17:03:19
	 */
	int updateByPrimaryKeySelective(KdiTraceMo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table KDI_TRACE
	 *
	 * @mbg.generated 2018-06-15 17:03:19
	 */
	int updateByPrimaryKey(KdiTraceMo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table KDI_TRACE
	 *
	 * @mbg.generated 2018-06-15 17:03:19
	 */
	List<KdiTraceMo> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table KDI_TRACE
	 *
	 * @mbg.generated 2018-06-15 17:03:19
	 */
	List<KdiTraceMo> selectSelective(KdiTraceMo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table KDI_TRACE
	 *
	 * @mbg.generated 2018-06-15 17:03:19
	 */
	boolean existByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table KDI_TRACE
	 *
	 * @mbg.generated 2018-06-15 17:03:19
	 */
	boolean existSelective(KdiTraceMo record);

	/**
	 * 根据物流订单ID删除其所有轨迹
	 * 
	 * @param logisticId
	 *            物流订单ID
	 */
	@Delete("delete from KDI_TRACE where LOGISTIC_ID=#{logisticId}")
	void delByLogisticId(Long logisticId);
}