kdi:
  issandbox: true
  kdniao:
    # 专门测试物流跟踪推送功能的账号和key
#    Ebusinessid: test1326761
#    apikey: 45f18644-a37c-4f26-b17b-6d25ca8bdbdd
    # 测试其它功能的账号和key
    Ebusinessid: 1326761
    apikey: ead9e2d4-346c-42c6-b391-a7bee4994f21
  # 各快递公司电子面单的参数《快递鸟电子面单参数配置对照表》
  shippers:
    # 百世快递
    HTKY:
      customername: testhtky
      customerpwd: testhtkypwd
      # 运费支付方式: 1-现付，2-到付，3-月结，4-第三方付
      paytype: 3
    YZPY:
      # 运费支付方式: 1-现付，2-到付，3-月结，4-第三方付
      paytype: 3
    # 顺丰速运
    SF:
      monthcode: "7553045845"
      # 运费支付方式: 1-现付，2-到付，3-月结，4-第三方付
      paytype: 1
    # 申通快递
    STO:
      customername: teststo
      customerpwd: teststopwd
      sendsite: teststosendsite
      # 运费支付方式: 1-现付，2-到付，3-月结，4-第三方付
      paytype: 1
    # 中通快递
    ZTO:
      customername: testzto
      customerpwd: testztopwd
      # 运费支付方式: 1-现付，2-到付，3-月结，4-第三方付
      paytype: 1
    # 圆通速递
    YTO:
      customername: testyto
      monthcode: testytomonthcode
      # 运费支付方式: 1-现付，2-到付，3-月结，4-第三方付
      paytype: 1